
artefacts_root: artefacts

data_ingestion:
  root_dir: artefacts/data_ingestion
  source_URL: https://github.com/donadviser/datasets/raw/master/data-don/spam_email.zip
  local_data_file: artefacts/data_ingestion/data.zip
  unzip_dir: artefacts/data_ingestion


data_validation:
  root_dir: artefacts/data_validation
  unzip_data_dir: artefacts/data_ingestion/email.csv
  STATUS_FILE: artefacts/data_validation/status.txt


data_transformation:
  root_dir: artefacts/data_transformation
  data_path: artefacts/data_ingestion/email.csv


model_trainer:
  root_dir: artefacts/model_trainer
  x_test_path: artefacts/data_transformation/x_test.csv
  x_train_path: artefacts/data_transformation/x_train.csv
  y_test_path: artefacts/data_transformation/y_test.csv
  y_train_path: artefacts/data_transformation/y_train.csv
  model_name: model.h5

model_evaluation:
  root_dir: artefacts/model_evaluation
  model_path: artefacts/model_trainer/model.h5
  metrics_json_file: artefacts/model_evaluation/metrics.json